In [1]:
!pip install tensorflow-text

In [2]:
import tensorflow_hub as hub
import tensorflow_text as text

In [3]:
preprocessing_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [4]:
bert_preprocessing_model = hub.KerasLayer(preprocessing_url)

In [5]:
text_test = ['Really liked the movie','I like cinematography']
text_processed = bert_preprocessing_model(text_test)
text_processed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [6]:
text_processed['input_mask']

# CLS Really liked the movie SEP ; so there are 6 ones.
# CLS I like cinematography SEP; so there are 5 ones.
# 128 is the maximum length of sentence.

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [7]:
text_processed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [8]:
text_processed['input_word_ids']

# CLS Really liked the movie SEP
# 101,  2428,  4669,  1996,  3185,   102,


# CLS I like cinematography SEP
# 101,  1045,  2066, 16434,   102

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  2428,  4669,  1996,  3185,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

Encoder URL

In [9]:
bert_model = hub.KerasLayer(encoder_url)
bert_results = bert_model(text_processed)
bert_results.keys()

dict_keys(['default', 'encoder_outputs', 'pooled_output', 'sequence_output'])

In [10]:
bert_results['pooled_output']

# These are the embedding vectors for two sentences.

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8263064 , -0.17278126,  0.27924013, ...,  0.15713035,
        -0.45232818,  0.7954692 ],
       [-0.8771158 , -0.29176295,  0.02833419, ...,  0.09874732,
        -0.6452149 ,  0.89032835]], dtype=float32)>

In [11]:
bert_results['sequence_output']

#These are the embeddings for each word in the sentence

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.09783484, -0.03506267,  0.04358425, ..., -0.06985385,
          0.22276464,  0.00362622],
        [ 0.48102134, -0.20802848,  0.24011154, ..., -0.24409075,
          0.9974468 , -0.2940345 ],
        [ 0.41661012, -0.51480633,  1.1655794 , ...,  0.16880813,
          0.30385143,  0.00870666],
        ...,
        [ 0.2524331 , -0.10780718,  0.48388675, ..., -0.0937157 ,
          0.18637109, -0.0528587 ],
        [ 0.23508075, -0.10369442,  0.50139844, ..., -0.09330641,
          0.17374349, -0.04942637],
        [ 0.08065768, -0.27257746,  0.5423633 , ...,  0.0235246 ,
          0.11328863, -0.05822545]],

       [[-0.02086344,  0.15232871, -0.15997295, ..., -0.0849948 ,
          0.35775068,  0.28517592],
        [ 0.23832995, -0.10287976,  0.18971658, ..., -0.08109708,
          0.61584616,  0.10237086],
        [ 0.5738043 ,  0.10930991,  0.8985311 , ...,  0.42202955,
          0.74049795, -0.06434388],
        ...,

In [12]:
len(bert_results['encoder_outputs'])
# This is becuase we are using bert base with 12 encoders

12

In [13]:
bert_results['encoder_outputs']
#Each layer has 768 size embedding vector

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.22413814,  0.06598763, -0.12141633, ...,  0.10352281,
           0.11091131,  0.0504744 ],
         [ 1.0873793 ,  1.1775429 ,  0.29433444, ...,  1.5940297 ,
           1.9120454 , -0.62365896],
         [-0.17793012,  0.60245115,  0.70869476, ..., -0.46072954,
           0.10279997,  0.03374783],
         ...,
         [-0.13997832, -0.22730705,  0.576831  , ...,  0.5289305 ,
          -0.09513379,  0.0949588 ],
         [-0.2148868 , -0.26212257,  0.4560125 , ...,  0.5649713 ,
          -0.00419325,  0.00845928],
         [-0.09613963, -0.19786616,  0.48470056, ...,  0.82535076,
          -0.25161666, -0.05972811]],
 
        [[ 0.14680892, -0.00785897, -0.0800485 , ...,  0.0275598 ,
           0.13790122,  0.05448858],
         [ 0.57063115,  1.1444637 , -0.469595  , ...,  0.55202854,
           1.0602752 ,  0.18420425],
         [ 0.00402201,  1.4841332 ,  0.4806977 , ..., -0.07598991,
           0.9810401 ,  0.01

In [14]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

#These both are same

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>